name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEVELOPER_DIR: /Applications/Xcode_26.0.app/Contents/Developer

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
    - name: Test
      run: swift test --filter "AoCTests.Day.*Tests/testDay.*_part[12]\(\)"
